name: Deploy to Remote Server

on:
  push:
    branches:
        ramzan118-patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@203.170.77.228 -p 22 << 'EOF'
          cd /var/www/html
          git stash
          git pull origin ramzan118-patch-1
          git stash pop
          npm install --force
          npm run build
          rm -rf /var/www/html/textutility/*
          cp -R /var/www/html/build/* /var/www/html/textutility/
          sudo systemctl restart nginx
        EOF